[package]
name = "modality-ingest-client"
version = "0.1.0"
edition = "2021"

[features]
default = []
test_support = []

[dependencies]
minicbor = { version = "0.13.1", features = ["std", "derive"] }
minicbor-io = {version = "0.8", features = ["async-io"]}
native-tls = "0.2.10"
thiserror = "1"
tokio = { version = "1", features = ["net", "time", "io-util"] }
tokio-native-tls = "0.3.0"
url = { version = "2.1" }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
#modality-auth-token = { path = "../modality-auth-token" }
