FROM quay.io/pypa/manylinux_2_28_x86_64
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup install 1.78
RUN pipx install maturin patchelf

COPY . /workdir
WORKDIR /workdir/python/auxon-sdk
RUN maturin build --manylinux 2_28 -i python3.8
